### ISSUE TITLE
vagrant setup

### ISSUE THREAD

**Issue by Rigel772** [LondonAppDev/course-rest-api#1]
Hello there, 
Following your instructions after vagrant up and ssh when executing
`mkvirtualenv profiles-api`
I am getting error:
`mkvirtualenv: command not found`
...
after some investigation, in the vagrant file we write virtualenv configurations into /home/ubuntu/.bashrc
while there is another .bashrc file in /home/vagrant which is actually being read after vagrant ssh
the `mkvirtualenv profiles-api` command works fine after adding `source /home/ubuntu/.bashrc` to .bashrc file in /home/vagrant folder...

can you explain how folders /home/ubuntu and /home/vagrant are related to each other?
Is adding `source /home/ubuntu/.bashrc` to .bashrc file in /home/vagrant folder right solution?
....it looks a bit strange....
:)
Thank you

**Comment by LondonAppDev** [comment]
This is an old post so apologies for the 3 year late response. We ask that all students post questions in the Q&A and we'll respond within 7 days.
