### ISSUE TITLE
This is not even the complete code!

### ISSUE THREAD

**Issue by mdalvi** [LondonAppDev/course-rest-api#2]
This is not even the complete code! Where is the complete code as per your course on Udemy?

**Comment by LondonAppDev** [comment]
Apologies, this project is for an older version of the course. 

The project for the most recent version is [profiles-rest-api](https://github.com/LondonAppDev/profiles-rest-api). It's also linked in the [Intro lesson](https://www.udemy.com/course/django-python-advanced/learn/lecture/12712403) of the course.

May I ask where you found the link to this project? This will help me update the link appropriately to help other students.

**Comment by mdalvi** [comment]
Thank you for the prompt response. Please note I found this repo under "Popular repositories" on your Github profile homepage.
